services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
